<?php
const PARAM_NAME_BASE64_URL = 'r64';
const PARAM_NAME_URL_ENCODED = 'uenc';

use Magento\Framework\App\Action\Action;

$products = $block->getProductCollection();
?>

<ul>
    <?php foreach ($products as $key => $product) :;
        $product_id = $product->getData('entity_id');
        $productInfo = $block->getProductById($product_id);
        $product_name = $productInfo->getName();
        $product_price = number_format(round($productInfo->getPrice()), 2);
        $product_url = $productInfo->getUrl_key();
        $product_image = $block->getImage($productInfo);

        ?>
        <li>
            <a class="product_item" href="<?php echo $block->getBaseUrl() . $product_url . '.html'; ?>">
                <div class="p-image"><img src="<?php echo $product_image ;?>" alt=""></div>
                <div class="p-name"><?php echo $product_name; ?></div>
                <div class="p-price"><?php echo "$" . $product_price; ?></div>
            </a>
            <?php $postParams = $block->getAddToCartPostParams($product); ?>
            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                <?php echo $block->getBlockHtml('formkey') ?>
                <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary">
                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                </button>
            </form>
        </li>
    <?php endforeach; ?>
</ul>
