<?php
/** @var \CS2\DuongDm\Block\Frontend\ListCategory $block */
$collectioncate = $block->getCategoryCollection();
?>
<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: center;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd;  }
    .post-id{width:2%} .post-name{width:30%}
</style>
<table>
    <?php
    foreach ($collectioncate as $key => $category):?>
        <tr>
            <td>
            <a href="<?= $block->getCategoryUrlById('blog_id',$category->getCategoryId()) ?>"><?=$category->getName()?></a>
            </td>
        </tr>;

    <?php
    endforeach;
    ?>
</table>



